services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      # docker-compose で alertmanager-discord を使う場合、external-urlの設定が必要。
      # Discordへのリクエストembeds[0].url に Discordにとっては無効なURLが入り、'{"embeds": ["0"]}'というエラーレスポンスが返ってきてしまう。
      # AlertManager からのリクエスト externalURL が alertmanager-discord から Discord へのリクエスト embeds[0].url に対応する。
      # AlertManagerの起動引数も同様。
      - '--web.external-url=https://example.com'
    ports:
      - 9090:9090
    restart: always
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--web.external-url=https://example.com'
    ports:
      - 9093:9093
    restart: always
  alertmanager_discord:
    image: rogerrum/alertmanager-discord:1.0.6
    container_name: alertmanager-discord
    ports:
      - 9094:9094
    environment:
      - DISCORD_WEBHOOK
      - DISCORD_USERNAME
      - DISCORD_AVATAR_URL
      - VERBOSE
    restart: always
  # request from amazon-dash
  simple-last-time-api-last-tooked-medicine:
    image: watahari/simple-last-time-api
    container_name: simple-last-time-api-last-tooked-medicine
    restart: always
    ports:
      - 8081:8080
