global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
        - node-exporter:9100
        - simple-last-time-api-last-tooked-medicine:8080
  - job_name: 'dyson'
    scrape_interval: 5m # not to reach API rate limit
    static_configs:
      - targets:
        - prometheus-dyson-exporter:9672
  - job_name: 'switchbot'
    scrape_interval: 5m # not to reach API rate limit
    metrics_path: /metrics
    http_sd_configs:
    - url: http://switchbot-exporter:8080/discover
      refresh_interval: 1d # no need to check for new devices very often
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: switchbot-exporter:8080
  - job_name: amedas
    # データの出典: amedas_exporter （ https://amedas.miiton.dev/ ）
    scrape_interval: 300s # must:200<interval, recommend:600>interval
    static_configs:
      - targets:
        - amedas.miiton.dev
