{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "location", "query": "Tokyo" }
  ]
 },
 "panels": [
  {
   "title": "次回服薬可能まで",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((last_posted_unixtime_seconds + 4 * 60 * 60) - time()) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "次回服薬可能日時",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_posted_unixtime_seconds * 1000 + 4 * 60 * 60 * 1000 > time() * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asia/Tokyo",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "前回服薬日時",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_posted_unixtime_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1週間の服薬回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(last_posted_unixtime_seconds{job=\"prometheus\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Environments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "気温",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "switchbot_meter_temperature", "legendFormat": "{{device_name}}" },
    { "expr": "temperature - 273.15", "legendFormat": "{{job}}" },
    {
     "expr": "avg_over_time(amedas_temperature{name=\"$location\"}[10m])",
     "legendFormat": "アメダス{{name_kanji}}"
    }
   ]
  },
  {
   "title": "湿度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "switchbot_meter_humidity", "legendFormat": "{{device_name}}" },
    { "expr": "humidity", "legendFormat": "{{job}}" },
    {
     "expr": "avg_over_time(amedas_humidity{name=\"$location\"}[10m])",
     "legendFormat": "アメダス{{name_kanji}}"
    }
   ]
  },
  {
   "title": "in",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scalar(switchbot_meter_temperature{device_name=\"Switchbot Hub 2\"})+scalar(temperature - 273.15))/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scalar(switchbot_meter_humidity{device_name=\"Switchbot Hub 2\"}) + scalar(humidity))/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switchbot_meter_temperature{device_name=\"防水温湿度計\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switchbot_meter_humidity{device_name=\"防水温湿度計\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "気圧",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "avg_over_time(amedas_normal_pressure{name=\"$location\"}[10m])",
     "legendFormat": "アメダス{{name_kanji}}"
    }
   ]
  },
  {
   "title": "降水量(10分)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time(amedas_precipitation_10m{name=\"$location\"}[10m])",
     "legendFormat": "アメダス{{name_kanji}}"
    }
   ]
  },
  { "title": "ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "機器状態",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    { "expr": "up", "legendFormat": "{{device_name}}{{instance}}" }
   ]
  }
 ]
}