apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://pi5:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.1.0
      cacheLevel: 'High'
  - name: GCalJSON
    type: yesoreyeram-infinity-datasource
    url: http://pi5:8082/events
